<?php

/**
 * @file
 * The Oops Logic module provides various business logic/workflow functionality for the platform.
 */

define('MENTOR_GROUP_TYPE', 'mentor_group');
define('MENTOR_GROUP_MEMBERSHIP_TYPE', 'mentor_group_membership');


function oops_logic_node_presave($node) {
    switch ($node->type) {
        case 'mentor_group':
            $node->field_group_members[LANGUAGE_NONE][0]['value'] = count(oops_utils_query_og_members($node->nid, 1));
            break;
    }
}

/**
 * Acts on a OG membership being inserted or updated.
 *
 * When a new group application is created we check group limits
 * If somehow the group limit is reached we close the group and eventually reject application
 *
 * This hook is invoked before the OG membership is saved to the database.
 *
 * @param OgMembership $og_membership
 *   The OG membership that is being inserted or updated.
 *
 * @see hook_entity_presave()
 */
function oops_logic_og_membership_update(OgMembership $og_membership) {
    if ($og_membership->entity_type == 'user') {
        $new_status = $og_membership->state;
        $old_status = $og_membership->original->state;
        $group = entity_load_single($og_membership->group_type, $og_membership->gid);
        $limit = $group->field_max_group_members[LANGUAGE_NONE][0]['value'];
        $active_members = count(oops_utils_query_og_members($og_membership->gid, 1));

        // CLOSE GROUP
        // pending to active
        if ($old_status == 1 && $new_status == 2) {

        }

        switch ($new_status) {
            case 1:

        }


        // OPEN GROUP
        // current status delete
        // update group member count
        $updated = FALSE;
        if (!$updated) {
            $group->field_group_members[LANGUAGE_NONE][0]['value'] = $active_members;
            entity_save($og_membership->group_type, $group);
            $updated = TRUE;
        }

    }
}

function oops_logic_form_og_ui_edit_membership_alter(&$form, &$form_state, $form_id) {
    $form['#validate'][] = 'oops_logic_og_ui_edit_membership_validate';
}

function oops_logic_og_ui_edit_membership_validate($form, &$form_state) {
    $values = $form_state['values'];
    $og_membership = $form_state['og_membership'];
    $new_status = $values['state'];
    $old_status = $og_membership->state;
    $group = entity_load_single($og_membership->group_type, $og_membership->gid);
    $limit = $group->field_max_group_members[LANGUAGE_NONE][0]['value'];
    $active_members = count(oops_utils_query_og_members($og_membership->gid, 1));
    // pending member is approved, check availability
    if (($old_status ==2 && $new_status == 1) && $active_members >= $limit) {
        form_set_error('submit', t('You can no longer add members to this group. This group has reached its maximum number of members! Consider increasing group membership limit.'));
    }
}

/**
 * Confirm subscribe form.
 */
function oops_logic_form_og_ui_confirm_subscribe_alter(&$form, &$form_state, $form_id) {
  global $user;
  $group = node_load($form['gid']['#value']);
  $member = oops_utils_query_og_membership_exists($user->uid, $state = NULL);
  if (count($member) > 0) {
    drupal_set_message(t('You have already applied to a mentor group.'));
    drupal_goto('user');
  }

  if ($group->type == MENTOR_GROUP_TYPE) {
    // replace default membership with custom mentor_group bundle
    $form_state['og_membership']->type = MENTOR_GROUP_MEMBERSHIP_TYPE;
    $og_membership = $form_state['og_membership'];
    field_attach_form('og_membership', $og_membership, $form, $form_state);

    // unset default og_membership_default field
    unset($form['og_membership_request']);
    unset($form_state['field']['og_memebership_request']);

    drupal_set_title(t('Apply for mentor group ' . $group->title));
  }

  $form['#after_build'][] = 'oops_logic_og_ui_confirm_subscribe_after_build';
  $form['#validate'][] = 'oops_logic_og_ui_confirm_subscribe_validate';

}

function oops_logic_form_og_ui_add_users_alter($form, &$form_state, $group_type, $gid) {
  $group = node_load($form['gid']['#value']);
  if ($group->type == MENTOR_GROUP_TYPE) {
    $form_state['og_membership']->type = MENTOR_GROUP_MEMBERSHIP_TYPE;
    $og_membership = $form_state['og_membership'];
    unset($form['membership_fields']);
    $form['membership_fields'] = array(
      '#prefix' => '<div id="og-ui-field-name">',
      '#suffix' => '</div>',
      '#tree' => TRUE,
      '#parents' => array('membership_fields'),
    );
    field_attach_form('og_membership', $og_membership, $form['membership_fields'], $form_state);

    unset($form_state['field']['#parents']['membership_fields']['#fields']['og_membership_request']);
  }
}

/**
function oops_logic_og_membership_presave(OgMembership $og_membership) {
  $og_membership->name = 'foo';
  dsm($og_membership);
  if ($og_membership->is_new) {
    $group = node_load($og_membership->gid);
    if ($group->type == MENTOR_GROUP_TYPE) {

    }
  }
}
 */

function oops_logic_og_ui_confirm_subscribe_after_build($form, &$form_state) {
  $path = drupal_get_path('module', 'oops_logic');
  drupal_add_js ("$path/youtube.js");
  drupal_add_js ("$path/youtube-process.js");
  return $form;
}

/**
 * Custom validate handler; Confirm OG membership.
 *
 * If group limit is reached while user submits join we invalidate the form and force group to invite only
 */
function oops_logic_og_ui_confirm_subscribe_validate($form, &$form_state) {
    $group_type = $form_state['values']['group_type'];
    $gid = $form_state['values']['gid'];
    $group = entity_load_single($group_type, $gid);
    $limit = $group->field_max_group_members[LANGUAGE_NONE][0]['value'];
    $query = new EntityFieldQuery();
    $query
        ->entityCondition('entity_type', 'og_membership', '=')
        ->propertyCondition('entity_type', 'user', '=')
        ->propertyCondition('gid', $gid, '=')
        ->propertyCondition('state', 1, '=');
    $result = $query->execute();
    $members = count($result['og_membership']) - 1;

    if ($members >= $limit) {
        $subscribe_model = $group->field_og_subscribe_settings[LANGUAGE_NONE][0]['value'];
        if ($subscribe_model != 'invitation') {
            $group->field_og_subscribe_settings[LANGUAGE_NONE][0]['value'] = 'invitation';
            node_save($group);
        }
        form_set_error('submit', t('You can no longer join this group. This group has reached its maximum number of members!'));
    }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the privacy settings fields.
 */
function oops_logic_form_mentor_group_node_form_alter(&$form, &$form_state) {
  //patched
  $form['field_og_subscribe_settings']['#type'] = 'hidden';
  $form['field_og_subscribe_settings'][LANGUAGE_NONE]['#required'] = FALSE;

  if (module_exists('og_access')) {
    // Display the private content checkbox only when "Joining requires approval"
    // is selected.
    $form['field_og_access_default_value']['#states'] = array(
      'visible' => array(
        ':input[name="field_og_subscribe_settings[' . LANGUAGE_NONE . ']"]' => array('value' => 'approval'),
      ),
    );

    $form['#after_build'] = array('oops_logic_form_group_node_after_build');
  }

  $form['#attached']['css'] = array(
    drupal_get_path('module', 'commons_groups') . '/css/commons_groups.css',
  );

  // The group access is set on commons_groups_node_presave().
  $form['group_access'][LANGUAGE_NONE]['#required'] = FALSE;
  $form['group_access']['#access'] = FALSE;

}

/**
 * After build callback for the group node form.
 *
 * Display the private content checkbox inside the privacy settings field.
 */
function oops_logic_form_group_node_after_build($form, $form_state) {
  $form['field_og_subscribe_settings'][LANGUAGE_NONE]['approval']['#suffix'] = render($form['field_og_access_default_value']);

  return $form;
}

function oops_logic_profile2_insert($profile) {
  $account = user_load($profile->uid);
  switch ($profile->type) {
    case 'student':
      $county = isset($profile->field_county_name[LANGUAGE_NONE][0]['value']) ? filter_xss($profile->field_county_name[LANGUAGE_NONE][0]['value']) : FALSE;
      if ($county) {
        $group = oops_logic_load_group_by_county($county);
        oops_logic_og_group($group, $account, $role = 2);
      }
      break;
    case 'librarian':
      $county = isset($profile->field_county_name[LANGUAGE_NONE][0]['value']) ? filter_xss($profile->field_county_name[LANGUAGE_NONE][0]['value']) : FALSE;
      if ($county) {
        $group = oops_logic_load_group_by_county($county);
        oops_logic_og_group($group, $account, $role = 3);
      }
      break;
  }
}

function oops_logic_profile2_update($profile) {
  $account = user_load($profile->uid);
  switch ($profile->type) {
    // register users in county level groups
    case 'student':
      $county = isset($profile->field_county_name[LANGUAGE_NONE][0]['value']) ? filter_xss($profile->field_county_name[LANGUAGE_NONE][0]['value']) : FALSE;
      if ($county) {
        $group = oops_logic_load_group_by_county($county);
        $membership = oops_utils_query_og_county_membership_exists($account->uid, $group->nid, $state = NULL);
        //dsm($membership);
        if (count($membership) == 0) {
          oops_logic_og_group($group, $account, $role = 2);
        }
      }
      break;
    case 'librarian':
      $county = isset($profile->field_county_name[LANGUAGE_NONE][0]['value']) ? filter_xss($profile->field_county_name[LANGUAGE_NONE][0]['value']) : FALSE;
      if ($county) {
        $group = oops_logic_load_group_by_county($county);
        $membership = oops_utils_query_og_county_membership_exists($account->uid, $group->nid, $state = NULL);
        if (count($membership) == 0) {
          oops_logic_og_group($group, $account, $role = 3);
        }
      }
      break;
  }
}

function oops_logic_load_group_by_county($county) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'node', '=')
    ->fieldCondition('field_county_name', 'value', $county)
    ->propertyCondition('type', 'group', '=');

  $result = $query->execute();
  if (isset($result['node'])) {
    $group_id = array_keys($result['node']);
    $group = entity_load('node', $group_id);
  }
  //dsm($county);
  //dsm($group);
  //dsm($group_id);
  return $group[$group_id[0]];
}

// Changes the users role in the group (1 = non-member, 2 = member, 3 = administrator member)
function oops_logic_og_group($group, $account, $role) {
  og_group('node', $group->nid, array(
    "entity type"       => "user",
    "entity"        => $account,
    "membership type"   => OG_MEMBERSHIP_TYPE_DEFAULT,
  ));
  og_role_grant('node', $group->nid, $account->uid, $role);
}

function oops_utils_query_og_county_membership_exists($uid, $gid, $state = NULL) {
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'og_membership', '=')
    ->propertyCondition('type', 'og_membership_type_default', '=')
    ->propertyCondition('entity_type', 'user', '=')
    ->propertyCondition('group_type', 'node', '=')
    ->propertyCondition('gid', $gid, '=')
    ->propertyCondition('etid', $uid, '=');

  if ($state != NULL) {
    $query->propertyCondition('state', $state, '=');
  }
  $result = $query->execute();
  $members = isset($result['og_membership']) ? $result['og_membership'] : array();
  return $members;
}

// TODO: form alter group edit and if limit < members only allow invite membership
// TODO: form alter group admin form and set group model to invitation when new members approved and limit is reached
// TODO: form alter group admin form and set group model to approval when users are deleted and places are made available


